### ISSUE TITLE
SteelSeries

### ISSUE THREAD

**Issue by ozzylamberth** [nicolas-van/steelseries#23]
What do you recommend to show a data generated every 15 seconds in my database hosted on a remote server, specifically in the following component or if you have any ideas that can guide me

function init() {
    // Initialzing gauge

	var sections = [steelseries.Section(0, 70, 'rgba(255, 0, 0, 1.0)'),
             steelseries.Section(70, 95, 'rgba(255, 255, 0, 1.0)'),
              steelseries.Section(95, 100, 'rgba(0, 255, 0, 1.0)') ];

    single1 = new steelseries.DisplaySingle('canvasSingle1', {
                        width: 120,
                        height: 50,
		    section: sections
                        })

**Comment by nicolas-van** [comment]
Hello,

Sorry but this question is not really related to steelseries. You should first learn more about JavaScript, how to fetch data at regular interval, how to alter the DOM dynamically, etc...

Once you have a working example that can update your value and display it, as example in a `<div>`, you can just replace the `<div>` by a `<steelseries-display-single>` or `<steelseries-display-multi>` component as indicated in the documentation and it should work flawlessly.

**Comment by ozzylamberth** [comment]
Good afternoon Nicolas-Van. Following your recommendations, I was able to display data from my Mysql Database in JavaScript through a JSON request.

![4](https://user-images.githubusercontent.com/7409604/167715644-ce776f2b-c13c-4a6b-b736-2c45b0f4023e.png)

This would be my structure only that the data loaded by JSON I can not show it in your DisplaySingle component but in the browser

I do my search
![1](https://user-images.githubusercontent.com/7409604/167716088-35a5856e-84e6-4b2e-812f-8094e0e6b86d.png)

This would be your component used DisplaySingle
![2](https://user-images.githubusercontent.com/7409604/167716224-744b375b-c5fa-4311-b31f-d09a1b83836c.png)

This is where I have my error, I am not asking you to do it, but I would like a second orientation, since through JSON I can show my data in a Speedometer and in graphs without any problem
![3](https://user-images.githubusercontent.com/7409604/167716411-3fc99337-bdf4-4050-b746-af259c6fecc1.png)
